### ISSUE TITLE
Problemas en visualización

### ISSUE THREAD

**Issue by christian102294** [LuisDavidCamacho/high-performance-pandas#1]
Hola Luis, Espero todo vaya bien

Al intentar visualizar el archivo  'high-performance-pandas/press/Presentation.ipynb' me aparece con un formato erroneo y con pocas lineas de texto

Gracias por tu presentación, saludos!

![captura](https://user-images.githubusercontent.com/45155827/53520231-2963d700-3aa3-11e9-99ab-599d61381211.PNG)

**Comment by LuisDavidCamacho** [comment]
Hola. Gracias por tu interés en este proyecto. Se que ha pasado un año pero hasta ahora tengo el tiempo de mejorar el trabajo publicado. El problema de visualización se debe a que el notebook contiene partes en HTML que son incompatibles con el renderer de GitHub. Quise dejar estas versiones en caso que quieran verlas como en la presentaciones.

Para resolver el problema de visualización añadí un nuevo notebook en la carpeta plain/en que puedes renderizar sin problema y sin tener que clonar el proyecto.
